version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          key: v1-deps-{{ checksum "requirements_test.txt" }}
      - run:
          name: Create virtualenv and install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install_requirements
      - save_cache:
          key: v1-deps-{{ checksum "requirements_test.txt" }}
          paths:
            - "venv"
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            make pytest -- --cov=. --cov-config=.coveragerc --cov-report=html --ignore=tests/load
            codecov

  test_load:
    working_directory: ~/greatcms
    docker:
      - image: circleci/python:3.6.6
        name: greatcms.trade.great
      - image: circleci/postgres:9.6.16-alpine-ram
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: test_greatcms
      - image: circleci/redis:5.0.7-alpine
    environment:
      HATCH_RATE: 2
      RUN_TIME: 30s
      NUM_CLIENTS: 10
      TEST_DATABASE_URL: postgresql://root@localhost/test_greatcms
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client-9.6
      - run:
          name: Create virtualenv and install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install_requirements
      - run:
          name: Database Setup
          command: |
            make secrets
            make database
            make manage migrate
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            mkdir results
            LOCUST_FILE=tests/load/test_mvp.py make test_load
      - store_test_results:
          path: ~/greatcms/results

  test_javascript:
    docker:
      - image: circleci/node:8.5.0
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package.json" }}
      - run:
          name: Install node modules
          command: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run:
          name: Run Javascript tests
          command: npm test

  flake8:
    docker:
    - image: circleci/python:3.6.6
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Run flake8
        command: |
          python3 -m venv venv
          . venv/bin/activate
          pip install flake8
          flake8

workflows:
  version: 2
  test_and_flake8:
    jobs:
      - test
      - test_javascript
      - test_load
      - flake8
